// Single source of truth for Spattoo's legal documents and the company details they
// reference. Consumed by the /terms /privacy /refund /grievance pages via
// components/LegalDocPage.tsx and the footer links in components/SiteFooter.tsx.
//
// PUBLISHED 13 August 2026 (v1.0, all four documents). Two things to know:
//   1. `effectiveDate` and LEGAL_STATUS drive what the page SHOWS. Anything left blank renders a
//      visible "[to be provided]", and LEGAL_STATUS is GLOBAL — it removes the draft banner from
//      every legal page at once, so a blank date on one document would leave that page looking
//      in-force with a placeholder on it. Fill all four together or none.
//   2. Versioning here backs DPDP Act 2023 demonstrable-consent: every published
//      version is retained + timestamped, and `version`/`docKey` are what a future
//      consent log (Layer 2) records a user's acceptance against. Never mutate a
//      published version in place — bump `version` and add a Document History row.

export const LEGAL_STATUS: "draft" | "published" = "published";

// Spattoo's OWN statutory identity + contacts (the platform operator FEELINGS&FLAVOURS —
// NOT a baker/tenant company; named spattoo_profile to avoid that confusion).
export const SPATTOO_PROFILE = {
  legalName: "FEELINGS&FLAVOURS (OPC) PRIVATE LIMITED",
  gstin: "36AAGCF5256J1ZD",
  cin: "U10712TS2025OPC201388", // e.g. "U15490TG2024OPC1XXXXX"
  registeredOffice: "VILLA NO 21, LIBDOM VILLAS, GANDHAMGUDA, PERENCHERUVU, Hydershahkote, Golconda, Hyderabad - 500091, Telangana", // full registered office address (Telangana)
  contactEmail: "care@spattoo.com",
  grievanceEmail: "care@spattoo.com", // dedicated mailbox recommended; falls back to contactEmail
  grievanceOfficerName: "Tammisetty Dayamani", // a real person resident in India (IT Rules 2021 / DPDP)
  grievanceOfficerDesignation: "Director",
} as const;

export type LegalSlug = "terms" | "privacy" | "refund" | "grievance";

export type LegalDoc = {
  slug: LegalSlug;
  docKey: string; // stable key the consent log (Layer 2) references — never rename
  title: string;
  navLabel: string; // short label for footer / cross-links
  file: string; // filename under content/legal/
  version: string;
  effectiveDate: string; // human-readable date, or "" until published
  description: string; // <meta description> + summary
};

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: "terms",
    docKey: "tos",
    title: "Terms of Service",
    navLabel: "Terms",
    file: "terms-of-service.md",
    // 1.1 (8 Sep 2026) — Section 7.2, on figures the Platform CALCULATES for making a cake
    // (tin sizes, heights, layers, bakes, barrels). Section 7 covered AI-generated output only;
    // these are computed from geometry, not generated by a model, so nothing said squarely that
    // they are a comparison to choose from rather than a recommendation or a measurement.
    // Bumped rather than edited in place: `version` is what a recorded consent points at, so a
    // published version must never change meaning underneath one.
    version: "1.1",
    effectiveDate: "8 September 2026",
    description:
      "The terms governing use of Spattoo — the technology platform for bakers and their customers.",
  },
  {
    slug: "privacy",
    docKey: "privacy",
    title: "Privacy Policy",
    navLabel: "Privacy",
    file: "privacy-policy.md",
    // 1.1 (6 Sep 2026) — Google Analytics on the marketing site. v1.0 stated we used no
    // behavioural-tracking cookies and promised to update this Policy if that changed;
    // this is that update. Bumped rather than edited in place: `version` is what a consent
    // log records an acceptance against, so a published version must never change meaning
    // underneath a recorded consent.
    version: "1.1",
    effectiveDate: "6 September 2026",
    description:
      "How Spattoo collects, uses, shares, and protects personal data, in line with the DPDP Act, 2023.",
  },
  {
    slug: "refund",
    docKey: "refund",
    title: "Refund & Cancellation Policy",
    navLabel: "Refund",
    file: "refund-and-cancellation-policy.md",
    version: "1.0",
    effectiveDate: "13 August 2026",
    description:
      "Cancellations and refunds for Spattoo baker subscriptions, and how cake orders are handled by the baker.",
  },
  {
    slug: "grievance",
    docKey: "grievance",
    title: "Grievance & Contact",
    navLabel: "Grievance",
    file: "grievance-and-contact.md",
    version: "1.0",
    effectiveDate: "13 August 2026",
    description:
      "How to contact Spattoo and reach our Grievance Officer under the IT Rules, 2021 and DPDP Act, 2023.",
  },
];

export const getLegalDoc = (slug: string): LegalDoc | undefined =>
  LEGAL_DOCS.find((d) => d.slug === slug);

// {{TOKEN}} values substituted into the markdown bodies at render. Anything unset
// shows "[to be provided]" so nothing silently ships blank.
export function legalTokens(doc: LegalDoc): Record<string, string> {
  const todo = "[to be provided]";
  return {
    LEGAL_NAME: SPATTOO_PROFILE.legalName,
    GSTIN: SPATTOO_PROFILE.gstin,
    CIN: SPATTOO_PROFILE.cin || todo,
    REGISTERED_OFFICE: SPATTOO_PROFILE.registeredOffice || todo,
    CONTACT_EMAIL: SPATTOO_PROFILE.contactEmail,
    GRIEVANCE_EMAIL: SPATTOO_PROFILE.grievanceEmail || SPATTOO_PROFILE.contactEmail,
    GRIEVANCE_OFFICER_NAME: SPATTOO_PROFILE.grievanceOfficerName || todo,
    GRIEVANCE_OFFICER_DESIGNATION: SPATTOO_PROFILE.grievanceOfficerDesignation || todo,
    EFFECTIVE_DATE: doc.effectiveDate || todo,
  };
}
